### ISSUE TITLE
sublister api error

### ISSUE THREAD

**Issue by ipk1** [0xdekster/deksterecon#2]
hey, 
great tool, thanks and congrats, however when i run it the sublister api throws an error

Error in Sublist3r API. error sending request for url (https://api.sublist3r.com/search.php?domain=domain.com): error trying to connect: dns error: failed to lookup address information: Name or service not known

thanks

**Comment by ipk1** [comment]
and gives this error "output file error (file)" for all the tools running, apache is installed

thanks

**Comment by 0xdekster** [comment]
@ipk1 Is there any issue in getting the Output ? I am looking into the error also.

**Comment by ipk1** [comment]
he look likes the issue is solved
